
name: Build

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          docker build --tag ironhalik/docker-waitforit .
      - name: Test
        run: docker run ironhalik/docker-waitforit -address https://example.com/ -status 200 -- echo "example.com is up"
      - name: Push
        run: |
          echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u ironhalik --password-stdin
          [ ${GITHUB_REF##*/} == "main" ] && TAG="latest" || TAG=${GITHUB_REF##*/}
          echo "Pushing tag: ${TAG}"
          docker tag ironhalik/docker-waitforit ironhalik/docker-waitforit:${TAG}
          docker push ironhalik/docker-waitforit:${TAG}