
name: Build

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Export extra envs
        uses: FranzDiebold/github-env-vars-action@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "ironhalik" --password-stdin
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ironhalik/docker-waitforit:${{ env.CI_REF_NAME }},ironhalik/docker-waitforit:${{ env.CI_SHA_SHORT }}
